from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

doc_src_path = Path(__file__).parent
root_path = doc_src_path.parent.parent
code_src_path = root_path / 'janim'

# Configurations


py_exclude_substrings = ['._', 'ui_', '__main__']
py_exclude_paths = [
    'janim/constants',
    'janim/cli',
    'janim/locale',
    'janim/gui/charts',
    'janim/gui/qdarkstyle',
    'janim/examples.py',
    'janim/logger.py',
]

extra_include_in_modules_rst = {
    # local_path: extra_list
    'janim': ['constants'],
}


# Validators


def match_py_exclude_substrings(name: str) -> bool:
    for substr in py_exclude_substrings:
        if substr in name:
            return True
    return False


def match_py_exclude_paths(path: Path) -> bool:
    path_str = path.relative_to(root_path).as_posix()
    for pattern in py_exclude_paths:
        if path_str == pattern:
            return True
    return False


# Process


@dataclass
class FileTreeNode:
    dirs: dict[str, FileTreeNode]
    files: list[str]

    def not_empty(self) -> bool:
        return bool(self.dirs) or bool(self.files)


def get_py_files_tree(path: Path) -> FileTreeNode:
    dirs: dict[str, FileTreeNode] = {}
    files: list[str] = []

    for subpath in sorted(path.iterdir()):
        if match_py_exclude_paths(subpath):
            continue

        if subpath.is_dir():
            subtree = get_py_files_tree(subpath)
            if subtree.not_empty():
                dirs[subpath.name] = subtree
        if subpath.is_file():
            if subpath.suffix == '.py' and not match_py_exclude_substrings(subpath.stem):
                files.append(subpath.stem)

    return FileTreeNode(dirs, files)


def walk_tree(node: FileTreeNode, local_path: Path):
    for name, child in node.dirs.items():
        walk_tree(child, local_path / name)
    for name in node.files:
        if name != '__init__':
            make_file_rst(local_path / name)

    make_dir_rst(node, local_path)


def make_file_rst(local_path: Path) -> None:
    name = local_path.name

    module_name = '.'.join(local_path.parts)
    rst_file = doc_src_path / local_path.with_suffix('.rst')

    if rst_file.exists():
        print('Exists:\t', module_name)
    else:
        rst_file.parent.mkdir(parents=True, exist_ok=True)
        with open(rst_file, 'wt') as file:
            file.write(
                f'{name}\n'
                f'{"=" * len(name)}\n'
                '\n'
                f'.. automodule:: {module_name}\n'
                '   :members:\n'
                '   :undoc-members:\n'
                '   :show-inheritance:\n\n'
            )
        print('Generated:\t', module_name)


def make_dir_rst(node: FileTreeNode, local_path: Path) -> None:
    name = local_path.name

    rst_file = doc_src_path / local_path / 'modules.rst'

    rst_file.parent.mkdir(parents=True, exist_ok=True)
    with open(rst_file, 'wt') as file:
        file.write(
            f'{name}\n'
            f'{"=" * len(name)}\n'
            '\n'
            '.. Do not modify this file, this file is generated by autodoc.py and your changes will lost.\n'
            '\n'
            '.. toctree::\n'
            '   :maxdepth: 1\n\n'
        )

        for dirname in node.dirs.keys():
            file.write(f'   {dirname}/modules.rst\n')

        extras = extra_include_in_modules_rst.get(local_path.as_posix(), None)
        if extras is not None:
            for extra in extras:
                file.write(f'   {extra}\n')

        for filename in node.files:
            if filename != '__init__':
                file.write(f'   {filename}\n')

        if '__init__' in node.files:
            module_name = '.'.join(local_path.parts)
            file.write(
                '\n'
                f'.. automodule:: {module_name}.__init__\n'
                '   :members:\n'
                '   :undoc-members:\n'
                '   :show-inheritance:\n\n'
            )


def generate_autodoc() -> None:
    tree = get_py_files_tree(code_src_path)
    walk_tree(tree, Path('janim'))


generate_autodoc()
