
class JAnimException(Exception): ...


class TimelineError(JAnimException): ...
class TimelineLookupError(TimelineError): ...
class StoreFailedError(TimelineError): ...
class StoreNotFoundError(TimelineError): ...


class CmptGroupLookupError(JAnimException): ...


class PointError(JAnimException): ...
class InvaildMatrixError(PointError): ...


class BooleanOpsError(JAnimException): ...


class AsTypeError(JAnimException): ...


class ColorNotFoundError(JAnimException): ...
class FontNotFoundError(JAnimException): ...
